baseURL = 'http://hiancemathbooks.com/'
languageCode = 'en-us'
title = 'Maximum Mathematics'
theme = 'relearn'

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)'], ['$', '$']]

[params]
    math = true
    collapsibleMenu = true

    [[params.boxStyle]]
        title = 'Definition'
        identifier = 'definition'
        color = '#305CDE'
        icon = 'book'

    [[params.boxStyle]]
        title = 'Example'
        identifier = 'example'
        color = '#228B22'
        icon = 'pencil'

    [[params.boxStyle]]
        title = 'Important'
        identifier = 'important'
        color = '#DAA520'
        icon = 'star'

    [[params.boxStyle]]
        title = "Theorem"
        identifier = "theorem"
        color = "#6C3BAA"
        icon = "pen-ruler"
